language: node_js
node_js: '10'
cache:
  directories:
    - ~/.cache

env:
  global:
    - DOCKER_REGISTRY="containers.schibsted.io"
    - DOCKER_IMAGE="${DOCKER_REGISTRY}/yapo/altiro-messaging"

before_script:
  - export BUILD_NAME=$(if [ -n "$TRAVIS_TAG" ]; then echo $TRAVIS_TAG; else echo ${TRAVIS_BRANCH//\//_}; fi)
  - echo $BUILD_NAME

install:
  - yarn install --frozen-lockfile

script:
  - yarn lint --fix
  - yarn build

after_failure:
  - reports-publisher

after_success:
  - reports-publisher
  - sudo start-docker-daemon
  - docker build -t "${DOCKER_IMAGE}:${BUILD_NAME}" .
  - docker login --username "${ARTIFACTORY_USER}" --password "${ARTIFACTORY_PWD}" "${DOCKER_REGISTRY}"
  - docker push "${DOCKER_IMAGE}:${BUILD_NAME}"

notifications:
  webhooks:
    - https://devhose.spt-engprod-pro.schibsted.io/devhose/travis

