language: generic

cache:
  directories:
    - ~/.cache

env:
  global:
    - DOCKER_REGISTRY="${ARTIFACTORY_DOCKER_REGISTRY}"
    - BRANCH=$([ ${TRAVIS_BRANCH} == master ] && echo latest || echo ${TRAVIS_BRANCH})
    - DOCKER_TAG="${TRAVIS_BRANCH}"
    - DOCKER=container_cache

before_install:
  - configure_jfrog_client
  - helm init --client-only

before_script:
  - export BUILD_NAME=$(if [ -n "$TRAVIS_TAG" ]; then echo $TRAVIS_TAG; else echo ${TRAVIS_BRANCH//\//_}; fi)
  - echo $BUILD_NAME

install:

script:

after_failure:
  - reports-publisher

after_success:
  - reports-publisher

deploy:
  - provider: script
    script: make build docker-publish
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST = false
  - provider: script
    script: make helm-publish
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST = false


