# Default values for smartbump.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
globals:
  env: reg

image:
  repository: containers.mpi-internal.com/yapo/altiro-messaging
  tag: "" 
  pullPolicy: IfNotPresent
  pullSecret: containers-mpi-internal-com

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
dontUseReleaseName: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

  tls: []


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
